### ISSUE TITLE
[Tasks] Checklist de Funcionalidades e Melhorias

### ISSUE THREAD

**Issue by leoeiji** [HighEloDevs/Analysis-Tool-for-Undergrad-Students-Web#1]
## Infraestrutura

- [ ] #2
- [ ] Definir o melhor banco de dados para o projeto
- [ ] Armazenamento em cloud para manter os projetos (.json)
- [ ] Aprimorar a infraestrutura do docker-compose
    - [ ] Otimizar os Dockerfiles
    - [ ] Otimizar o prod.yml
    - [ ] Otimizar o dev.yml

## Backend

- [ ] Adicionar uma função para parsear a função de ajuste
- [ ] Adicionar função para ajustar
- [ ] Banco de dados para armazenar os projetos de cada usuário

## Frontend

- [ ] Implementar o ajuste de funções
